### ISSUE TITLE
Feature: User can confirm or cancel when deleting a list item

### ISSUE THREAD

**Issue by yunyunliu** [yunyunliu/ajax-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can confirm or cancel deleting a list item 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user clicks the caught checkbox input, a modal will appear asking the user to confirm or cancel the delete

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] add style the dialog and button html elements that will be used as the modal  
- [ ] add event listener to rows containing cancel and delete buttons
  - [ ] handler only responds to clicks on button elements
  - [ ] if delete button is clicked; the the exiting delete functionality happens and modal closes
  - [ ] if cancel button is clicked;  modal simply closes
  - [ ] figure out if it's possible to add a transition onto elements being removed
  - 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
