### ISSUE TITLE
Feature: User can select a month and view all fish  available that month

### ISSUE THREAD

**Issue by yunyunliu** [yunyunliu/ajax-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select a month and view all fish  available that month

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the 'date' view, user selects a month using a dropdown; and a hemisphere from another dropdown; after clicking a 'find' button, user will be shown a list of available fish in that month and hemisphere

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a 'date' view
  - [ ] make sure it has the attribute 'data-view'
  - [ ] add a form element and select elements for choosing month and hemisphere
  - [ ] style to be consistent other views 
- [ ] create 'date-results-view'
  - [ ] even though the list items will eventually by generated with js; add the html and css for some dummy list items to help visualize it 
 - [ ] make sure you can access all fish data
 - [ ] 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by yunyunliu** [comment]
Not practical to implement because api does have many endpoints and the this app has no database
