### ISSUE TITLE
Feature: User can navigate to previous views by clicking a 'back' button

### ISSUE THREAD

**Issue by yunyunliu** [yunyunliu/ajax-project#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
 User can navigate to previous views by clicking a 'back' button

add a 'history' array to the data object. each element in the array contains the data necessary to reconstruct the view
data object also has a counter to keep track of which index the current view is. 
history object stories the past 5 view so you can navigate back and forwards between the by clicking buttons

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ]  find suitable icons
- [ ] add html for arrow buttons
- [ ]  style buttons
  - [ ]  when at the last index of the history array, the 'forward' button should be disabled; when at the first index. the 'back' button is disabled
  - [ ] - [ ] add 'history' and viewCounter  property to data object
  - [ ] history initialized as an empty array and viewCounter as 0;
  - [ ] this should be indicated by  a 'faded out' look on the button
- [ ] reloading page should clear the history array and zero the counter
- [ ] add functionality in 'changeView' function push information about the current view to the history object and increment or decrement viewCounter
- [ ]  make sure that viewCounter is correctly keeping track of views ie. the element at index viewCounter of history can be used to create the appropriate view
- [ ] make sure page matches the data
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by yunyunliu** [comment]
Come back to this later.
