### ISSUE TITLE
Feature: User can modify items on their ‘to-catch’ list

### ISSUE THREAD

**Issue by yunyunliu** [yunyunliu/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add and edit comments about the creatures on the To-Catch list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Clicking on the pen icon of a creature in list view will open a modal with either a blank textarea if there were no previous comments, or with a textarea prepopulated with the previous comment

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-24 at 4 17 42 PM](https://user-images.githubusercontent.com/45185196/134748645-ceae0b6c-3354-4889-983b-ec607367083f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] add comments property to objects stored in catchlist
- [x] add HTML for modal , textarea, and the buttons on it
- [x] style modal, textarea and buttons to match wireframe
- [x] add a click handler to <ul> element that responds to user clicking any of the pen icons  on the list elements
  - [ ] handler should open edit modal
  - [ ] set the data.editing property to the id of the entry
- [ ] add handlers to the  'cancel' and 'done' buttons of the modal
  - [x] handlers update the item with the user input from textarea and closes modal  or just closes modal
  - [ ] handlers set data.editiing back to null;
  - [ ] handlers remove the original item from catchlist and add the updated item to the front of catchlist
 - make sure data.editing is set back to null beforeunload
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
